### PR TITLE
ShadowDOM <3 MutationObserver

### PR DESCRIPTION
**Pull request by arv**
If MutationObserver polyfill is added after the shadow dom polyfill this should
work. Since observe is sometimes called with non wrapped nodes we need to wrap
in that case.

### CODE REVIEW

**Comment by dfreedm** [comment]
DOMNodeRemoved probably needs the wrapping too right?

**Comment by arv** [comment]
It is only `relatedNode` that is not wrapped so it does look correct to.

**Comment by arv** [comment]
This depends on:

https://github.com/toolkitchen/ShadowDOM/pull/144
https://github.com/toolkitchen/ShadowDOM/pull/145

**Comment by dfreedm** [comment]
All the deps are merged, merging.

**Pull request merged**
